const QUEUE_NAMES = {
  FIND_OBJECTS: 'find-objects',
  NOTIFICATION_DISCORD: 'notification-discord',
  NOTIFICATION_GAME: 'notification-in-game',
  SCAN_KINGDOM: 'scan-kingdom'
}

const JOB_TYPES = QUEUE_NAMES

const PRIORITY = {
  CRITICAL: 1,
  HIGH: 2,
  NORMAL: 3,
  LOW: 4,
  IDLE: 5
}

const DEFAULT_KINGDOM = 'CONFIG:DEFAULT_KINGDOM'
const ACTIVE_CHAT_CHANNEL = 'CONFIG:ACTIVE_CHAT_CHANNEL'
const SCAN_OTHER_KINGDOMS_KEY = 'TIMERS:SCAN_OTHER_KINGDOMS_KEY'

module.exports = {
  QUEUE_NAMES,
  JOB_TYPES,
  PRIORITY,
  DEFAULT_KINGDOM,
  ACTIVE_CHAT_CHANNEL,
  SCAN_OTHER_KINGDOMS_KEY
}
